### ISSUE TITLE
Impossible to build: 

### ISSUE THREAD

**Issue by alexorbit** [exteso/alf.io-PI#27]
totally impossible to build. i have done everything. 

> Task :backend:discoverMainScriptsExtensions
> Task :backend:compileKotlin UP-TO-DATE
> Task :backend:processResources UP-TO-DATE
> Task :backend:compileJava NO-SOURCE
> Task :backend:classes UP-TO-DATE
> Task :backend:findMainClass
> Task :backend:inspectClassesForKotlinIC UP-TO-DATE
> Task :frontend:compileJava NO-SOURCE
> Task :frontend:nodeSetup UP-TO-DATE
> Task :frontend:npmSetup UP-TO-DATE
> Task :frontend:npm_install

> canvas@1.6.11 install /etc/alfio/alf.io-PI/frontend/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/canvas/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/canvas/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> node-sass@4.10.0 install /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Unable to save binary /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor/linux-arm-64 : { Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:753:3)
    at sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor' }

> node-sass@4.11.0 install /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
> node scripts/install.js

Unable to save binary /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor/linux-arm-64 : { Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:753:3)
    at sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor' }

> node-sass@4.10.0 postinstall /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/build.js

Building: /etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node /etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node',
gyp verb cli   '/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.0
gyp verb command install [ '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.0
gyp verb ensuring nodedir is created /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp/10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

> node-sass@4.11.0 postinstall /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
> node scripts/build.js

Building: /etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node /etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node',
gyp verb cli   '/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.0
gyp verb command install [ '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.0
gyp verb ensuring nodedir is created /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp/10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/@angular-devkit/build-angular/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-27T07_43_41_304Z-debug.log

> Task :frontend:npm_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:npm_install'.
> Process 'command '/etc/alfio/alf.io-PI/frontend/.gradle/npm/npm-v6.4.1/bin/npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 31s
8 actionable tasks: 3 executed, 5 up-to-date
--------------------------------------------------------------------------

so, i've tried as root [sudo su] then i got this error:

> Task :backend:discoverMainScriptsExtensions
> Task :backend:compileKotlin UP-TO-DATE
> Task :backend:processResources UP-TO-DATE
> Task :backend:compileJava NO-SOURCE
> Task :backend:classes UP-TO-DATE
> Task :backend:findMainClass
> Task :backend:inspectClassesForKotlinIC UP-TO-DATE
> Task :frontend:compileJava NO-SOURCE
> Task :frontend:nodeSetup UP-TO-DATE
> Task :frontend:npmSetup UP-TO-DATE
> Task :frontend:npm_install

> canvas@1.6.11 install /etc/alfio/alf.io-PI/frontend/node_modules/canvas
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/canvas/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/canvas/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/.gradle/npm/npm-v6.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> node-sass@4.10.0 install /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Unable to save binary /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor/linux-arm-64 : { Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:753:3)
    at sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor' }

> node-sass@4.11.0 install /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
> node scripts/install.js

Unable to save binary /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor/linux-arm-64 : { Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:753:3)
    at sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/etc/alfio/alf.io-PI/frontend/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path:
   '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/vendor' }

> node-sass@4.10.0 postinstall /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/build.js

Building: /etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node /etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node',
gyp verb cli   '/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.0
gyp verb command install [ '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.0
gyp verb ensuring nodedir is created /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp/10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

> node-sass@4.11.0 postinstall /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
> node scripts/build.js

Building: /etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node /etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node',
gyp verb cli   '/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.0
gyp verb command install [ '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '10.15.0' ]
gyp verb install input version string "10.15.0"
gyp verb install installing version: 10.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.0
gyp verb ensuring nodedir is created /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp/10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.0' ]
gyp verb remove using node-gyp dir: /etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 10.15.0
gyp verb remove removing development files for version: 10.15.0
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/etc/alfio/alf.io-PI/frontend/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/etc/alfio/alf.io-PI/frontend/node/node-v10.15.0-linux-armv7l/bin/node" "/etc/alfio/alf.io-PI/frontend/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /etc/alfio/alf.io-PI/frontend/node_modules/node-sass
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/@angular-devkit/build-angular/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-27T07_43_41_304Z-debug.log

> Task :frontend:npm_install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:npm_install'.
> Process 'command '/etc/alfio/alf.io-PI/frontend/.gradle/npm/npm-v6.4.1/bin/npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 31s
8 actionable tasks: 3 executed, 5 up-to-date

**Comment by alexorbit** [comment]
then i realize that permission issue was because i was not at the user HOME directory. 
so i got this:
pi@raspberrypi:~/alf.io-PI $ ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-5.1-all.zip
............................................................................................................................

Welcome to Gradle 5.1!

Here are the highlights of this release:
 - Control which dependencies can be retrieved from which repositories
 - Production-ready configuration avoidance APIs

For more details see https://docs.gradle.org/5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type CrossBuildFileHashCache using BuildSessionScopeServices.createCrossBuildFileHashCache().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 15s

**Comment by cbellone** [comment]
Hi @alexorbit 
sorry for your troubles building this project...
To be completely honest we've never tried building it on a raspbian (or on a RaspberryPI) anyway, so you're the first one :-)
Since the backend runs on a JVM, there's no need to perform the build on ARM, so we do it on our dev machines / travis (https://travis-ci.org/alfio-event/alf.io-PI). But if you've time to explore this, please do, it would be great to set up an automated build on an actual RPI.

That being said, a couple of comments / suggestions:

1. if you're trying to setup your check-in station, please consider using the automated installer https://github.com/alfio-event/alf.io-PI/releases/tag/v0.9.6 . 
Please note that sometimes - depending on the raspbian version and on your configured mirror, the script could fail. We're working on it, please let us know if this is the case

2. the master branch is a WIP and it is possible that the build fails. Please make sure that you're building https://github.com/alfio-event/alf.io-PI/tree/0.9-maintenance

3. Please try to relaunch the build with the --debug option. And please update the java virtual machine version to the latest available on raspian (which should be JDK9). The default JVM is ~5 years old...

our plan for 1.0 would be to download and build a custom version of OpenJDK 11 and include it in the generated .deb

**Comment by alexorbit** [comment]
hey @cbellone thank you for the help, it works fine with a fresh install, it run at first, but i'm unable to login at the backend, i got this message when i try to login at  8080/admin :

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Apr 27 08:17:54 CDT 2019
There was an unexpected error (type=Forbidden, status=403).
Access is denied

may i have made something wrong?

**Comment by alexorbit** [comment]
> hey @cbellone thank you for the help, it works fine with a fresh install, it run at first, but i'm unable to login at the backend, i got this message when i try to login at 8080/admin :
> 
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Sat Apr 27 08:17:54 CDT 2019
> There was an unexpected error (type=Forbidden, status=403).
> Access is denied
> 
> may i have made something wrong?

sorry man, i[ve found the password at the logs.

best.
